import "server-only";
import type { OfferRow } from "@/server/db/repositories/offer";

/**
 * The one decision point every future payment integration plugs into —
 * "offer → checkout → order → order_items → attribution → analytics"
 * (Block 05 brief). Nothing here processes a real payment: this is the
 * abstraction layer so that DOES happen (Hotmart, Stripe, Mercado Pago,
 * a future first-party checkout) is a matter of setting
 * `offer.checkout_provider`/`checkout_url` on existing rows, never
 * restructuring this function's callers (`/api/checkout/[offerSlug]`).
 *
 * Three outcomes, deliberately not four: this app has no real checkout
 * of its own yet, so "internal" isn't wired to anything real — it
 * resolves the same safe way "unavailable" does, a lead-capture
 * fallback, until a future block actually builds one. `quote` never
 * pretends a fixed-price checkout exists for something that isn't
 * fixed-price (a B2B show, high-ticket coaching).
 */
export interface CheckoutDestination {
  kind: "external" | "quote" | "unavailable";
  url: string;
}

/** Where /contacto sends a lead generated by a checkout that isn't a real checkout yet. */
function quoteFallback(offerSlug: string, contactTopic: string): string {
  const params = new URLSearchParams({ topic: contactTopic, offer: offerSlug });
  return `/contacto?${params.toString()}`;
}

export function resolveCheckoutDestination(offer: OfferRow, contactTopic = "productos"): CheckoutDestination {
  if (!offer.active) {
    return { kind: "unavailable", url: quoteFallback(offer.slug, contactTopic) };
  }

  if (offer.purchaseType === "quote") {
    return { kind: "quote", url: quoteFallback(offer.slug, contactTopic) };
  }

  if (offer.checkoutProvider === "unavailable" || offer.checkoutProvider === "internal") {
    // 'internal' is reserved for a future first-party checkout this app
    // doesn't have yet — same safe fallback as 'unavailable' until it does.
    return { kind: "quote", url: quoteFallback(offer.slug, contactTopic) };
  }

  if (offer.checkoutUrl) {
    return { kind: "external", url: offer.checkoutUrl };
  }

  // A real provider is set but checkout_url is missing — misconfiguration,
  // not a reason to send a visitor to a broken link.
  return { kind: "unavailable", url: quoteFallback(offer.slug, contactTopic) };
}
